Add integration test for query event API
byliuyang/Growth pull request #20
Opened 2018-10-21 04:30 UTC by byliuyang

2018-10-21 05:19 UTC, CreatCodeBuild commented on integration_test.go
> +			assert.Nil(t, err)
use `require`

2018-10-21 20:57 UTC, CreatCodeBuild commented on gql/api_test.go
> +package gql_test
Don't do this. One directory should only have one package. Put it under `gql/gqltest/*`

2018-10-21 20:58 UTC, CreatCodeBuild commented on gql/api_test.go
> +	"github.com/stretchr/testify/require"
Format imports.

2018-10-21 21:01 UTC, CreatCodeBuild commented on gql/api_test.go
> +					expectedResponse: `{"errors":[{"message":"event:10 not found","path":["event"]}],"data":{"event":null}}`,
As we have discussed, define our own error types in graphql schema. Errors in `"errors"` json field should represent GraphQL errors instead of business errors.

Define our own error types have 2 benefits:
1. The FE will know what errors to expect, because schema serves as documentation.
2. It's implementation agnostic. If we switch GraphQL library or Language, the error definitions are kept.

2018-10-21 21:03 UTC, CreatCodeBuild commented on gql/api_test.go
> +					expectedResponse: `{"errors":[{"message":"event:10 not found","path":["event"]}],"data":{"event":null}}`,
For example
```
query {
   getEvent(): GetEventRet
}

type GetEventRet {
  event: Event
  error: YourErrorType # which is likely to be a union type.
}
```

2018-10-21 21:05 UTC, CreatCodeBuild requested changes
1. Address my comments
2. Please also refactor the usecase code so that it is an interface which could be injected into graphql resolvers. GraphQL resolvers should not import anything about datastores.

2018-11-07 06:50 UTC, byliuyang commented
@CreatCodeBuild Will address your comment on Wednesday.

2018-11-08 03:45 UTC, byliuyang commented on gql/api_test.go
> +					expectedResponse: `{"errors":[{"message":"event:10 not found","path":["event"]}],"data":{"event":null}}`,
@CreatCodeBuild I am confused.

2019-01-02 18:33 UTC, closed without merging